include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/generated/**

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 7
    number-of-parameters: 5
    source-lines-of-code: 60
    lines-of-code: 80
    technical-debt: 1
  metrics-exclude:
    - test/**
    - modules/**/test/**
  rules-exclude:
    - test/**
    - modules/**/test/**
  rules:
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-late-keyword
    - avoid-unnecessary-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - member-ordering-extended
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
    - no-object-declaration
    - prefer-correct-identifier-length:
        max-identifier-length: 30
        min-identifier-length: 2
    - prefer-first
    - prefer-last
    - always-remove-listener
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-correct-type-name:
        min-length: 3
        max-length: 40
